version: '3.9'

services:
  ultravox:
    build: .
    ports:
      - "8082:7860"
    environment:
      - STT_URL=http://whispercpp:9000/transcribe
      - TTS_URL=http://piper:10200/speak
      - LANGUAGE_SUPPORT=de,en
      - ENABLE_TWILIO=true
      - TWILIO_WEBHOOK_SECRET=zPs3IpdNpeUmrqgsx3h6
    depends_on:
      - whispercpp
      - piper
    command: bash -c "poetry install && poetry run python -m ultravox.tools.gradio_demo"

  whispercpp:
    image: ghcr.io/ggerganov/whisper.cpp:main
    ports:
      - "9000:9000"
    command: --language auto

  piper:
    image: rhasspy/wyoming-piper:latest
    ports:
      - "10200:10200"
    volumes:
      - ./piper/models:/data
    environment:
      - VOICE=de_DE-thorsten-high
    command: '--voice de_DE-thorsten-high'
